In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import numpy as np

In [4]:
array = np.random.randint(1, 50, size = (10))
array

array([31, 46, 27, 26, 33, 22, 20,  5, 32, 42], dtype=int32)

In [5]:
num = np.mean(array)
num

np.float64(28.4)

In [6]:
array1 = np.random.randint(1, 10, size = (2,3))
array1

array([[8, 1, 2],
       [2, 4, 8]], dtype=int32)

In [7]:
array2 = np.random.randint(1, 10, size = (2,3))
array2

array([[3, 4, 3],
       [1, 9, 2]], dtype=int32)

In [8]:
new_array = np.add(array1, array2)
new_array

array([[11,  5,  5],
       [ 3, 13, 10]], dtype=int32)

In [10]:
array3 = np.random.randint(1, 100, size = (20)) 
array3

array([31, 61, 93, 79,  4, 16, 62, 40, 20, 10, 87, 38, 89, 28, 92, 28, 62,
       65, 94, 12], dtype=int32)

In [12]:
filter_arr = array3[array3 > 50]
len(filter_arr)

10